### build stage
FROM node:lts-alpine

# make the current folder the current working directory
WORKDIR /

# copy both 'package.json' and 'package-lock.json' (if available)
COPY yarn.lock ./

# install project dependencies
RUN yarn

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

# build app for production with minification
RUN npm run build

EXPOSE 8080
CMD ["npm", "run", "serve"]